masterData = [
  {
    id: 1,
    name: "JACKET",
    title: "Mens Winter Leathers Jackets",
    imgOneC: "../img/Arrivals/1.jpeg",
    imgOne: "img/Arrivals/1.jpeg",
    imgTow: "img/Arrivals/1 (2).jpeg",
    price: 48.0,
    priceB: 75.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 2,
    name: "SHIRT",
    title: "Pure Garment Dyed Cotton Shirt",
    imgOne: "img/Arrivals/2.jpeg",
    imgOneC: "../img/Arrivals/2.jpeg",
    imgTow: "img/Arrivals/2 (2).jpeg",
    price: 54.0,
    priceB: 56.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 3,
    name: "JACKET",
    title: "MEN Yarn Fleece Full-Zip Jacket",
    imgOne: "img/Arrivals/3.jpeg",
    imgOneC: "../img/Arrivals/3.jpeg",
    imgTow: "img/Arrivals/3 (2).jpeg",
    price: 58.0,
    priceB: 65.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 4,
    name: "SKIRT",
    title: "Black Floral Wrap Midi Skirt",
    imgOne: "img/Arrivals/4.jpeg",
    imgOneC: "../img/Arrivals/4.jpeg",
    imgTow: "img/Arrivals/4 (2).jpeg",
    price: 25.0,
    priceB: 35.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 5,
    name: "CASUAL",
    title: "Casual Men's Brown Shoes",
    imgOne: "img/Arrivals/5.jpeg",
    imgOneC: "../img/Arrivals/5.jpeg",
    imgTow: "img/Arrivals/5 (2).jpeg",
    price: 48.0,
    priceB: 75.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 6,
    name: "WATCHES",
    title: "Pocket Watch Leather Pouch",
    imgOne: "img/Arrivals/6.jpeg",
    imgOneC: "../img/Arrivals/6.jpeg",
    imgTow: "img/Arrivals/6 (2).jpeg",
    price: 48.0,
    priceB: 75.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 7,
    name: "WATCHES",
    title: "Smart Watche Vital Plus",
    imgOne: "img/Arrivals/7.jpeg",
    imgOneC: "../img/Arrivals/7.jpeg",
    imgTow: "img/Arrivals/7 (2).jpeg",
    price: 48.0,
    priceB: 75.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 8,
    name: "PARTY WEAR",
    title: "Womens Party Wear Shoes",
    imgOne: "img/Arrivals/8.jpeg",
    imgOneC: "../img/Arrivals/8.jpeg",
    imgTow: "img/Arrivals/8 (2).jpeg",
    price: 48.0,
    priceB: 75.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 9,
    name: "JACKET",
    title: "Mens Winter Leathers Jackets",
    imgOne: "img/Arrivals/9.jpeg",
    imgOneC: "../img/Arrivals/9.jpeg",
    imgTow: "img/Arrivals/9 (2).jpeg",
    price: 48.0,
    priceB: 75.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 10,
    name: "SPORTS",
    title: "Mens Winter Leathers Jackets",
    imgOne: "img/Arrivals/10.jpeg",
    imgOneC: "../img/Arrivals/10.jpeg",
    imgTow: "img/Arrivals/10 (2).jpeg",
    price: 48.0,
    priceB: 75.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 11,
    name: "FORMAL",
    title: "Mens Winter Leathers Jackets",
    imgOne: "img/Arrivals/11.jpeg",
    imgOneC: "../img/Arrivals/11.jpeg",
    imgTow: "img/Arrivals/11 (2).jpeg",
    price: 48.0,
    priceB: 75.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 12,
    name: "SHORTS",
    title: "Mens Winter Leathers Jackets",
    imgOne: "img/Arrivals/12.jpeg",
    imgOneC: "../img/Arrivals/12.jpeg",
    imgTow: "img/Arrivals/12 (2).jpeg",
    price: 48.0,
    priceB: 75.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 13,
    name: "SHORTS",
    title: "Mens Winter Leathers Jackets",
    imgOne: "img/Arrivals/13.jpeg",
    imgOneC: "../img/Arrivals/13.jpeg",
    imgTow: "img/Arrivals/13 (2).jpeg",
    price: 48.0,
    priceB: 75.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 14,
    name: "SHORTS",
    title: "Mens Winter Leathers Jackets",
    imgOne: "img/Arrivals/14.jpeg",
    imgOneC: "../img/Arrivals/14.jpeg",
    imgTow: "img/Arrivals/14 (2).jpeg",
    price: 48.0,
    priceB: 75.0,
    imMe: "No",
    count: 1,
  },
  {
    id: 15,
    name: "SHORTS",
    title: "Mens Winter Leathers Jackets",
    imgOne: "img/Arrivals/15.jpeg",
    imgOneC: "../img/Arrivals/15.jpeg",
    imgTow: "img/Arrivals/15 (2).jpeg",
    price: 48.0,
    priceB: 75.0,
    imMe: "No",
    count: 1,
  },
];
